# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import contracts_pb2 as contracts__pb2


class WhisperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAudio = channel.unary_unary(
                '/WhisperService/ProcessAudio',
                request_serializer=contracts__pb2.ProcessAudioRequest.SerializeToString,
                response_deserializer=contracts__pb2.ProcessAudioReply.FromString,
                )


class WhisperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhisperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAudio,
                    request_deserializer=contracts__pb2.ProcessAudioRequest.FromString,
                    response_serializer=contracts__pb2.ProcessAudioReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WhisperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WhisperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WhisperService/ProcessAudio',
            contracts__pb2.ProcessAudioRequest.SerializeToString,
            contracts__pb2.ProcessAudioReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
