version: "3.7"

services:
  sd:
    image: mgrcar/sd:0.1
    build: .
    ports:
      - "7860:7860"
    entrypoint:
      - tail
      - -f
      - /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./files:/files
      - ./models:/root/sd/models
      - ./extensions:/root/sd/extensions
      - ./cache:/root/.cache
