version: "3.7"

services:
  whisper:
    image: mgrcar/whisper:0.1
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./files:/files
      - ./models:/models      
