# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ontracts.proto\"4\n\x10\x43\x61lculateRequest\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x12\n\n\x02op\x18\x03 \x01(\t\" \n\x0e\x43\x61lculateReply\x12\x0e\n\x06result\x18\x01 \x01(\x03\"/\n\x0bTemperature\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\x32`\n\x03Svc\x12/\n\tCalculate\x12\x11.CalculateRequest\x1a\x0f.CalculateReply\x12(\n\x06Median\x12\x0c.Temperature\x1a\x0c.Temperature(\x01\x30\x01\x42\t\xaa\x02\x06Sharedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\006Shared'
  _globals['_CALCULATEREQUEST']._serialized_start=19
  _globals['_CALCULATEREQUEST']._serialized_end=71
  _globals['_CALCULATEREPLY']._serialized_start=73
  _globals['_CALCULATEREPLY']._serialized_end=105
  _globals['_TEMPERATURE']._serialized_start=107
  _globals['_TEMPERATURE']._serialized_end=154
  _globals['_SVC']._serialized_start=156
  _globals['_SVC']._serialized_end=252
# @@protoc_insertion_point(module_scope)
