# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contracts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ontracts.proto\"\x1e\n\x0eProcessRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1d\n\x0cProcessReply\x12\r\n\x05reply\x18\x01 \x01(\t29\n\x0cModelService\x12)\n\x07Process\x12\x0f.ProcessRequest\x1a\r.ProcessReplyB\x17\xaa\x02\x14OddbitAi.ModelServerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contracts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\024OddbitAi.ModelServer'
  _globals['_PROCESSREQUEST']._serialized_start=19
  _globals['_PROCESSREQUEST']._serialized_end=49
  _globals['_PROCESSREPLY']._serialized_start=51
  _globals['_PROCESSREPLY']._serialized_end=80
  _globals['_MODELSERVICE']._serialized_start=82
  _globals['_MODELSERVICE']._serialized_end=139
# @@protoc_insertion_point(module_scope)
